const subjects = [
    `Microchips in our genitals`,
    `Bees`,
    `Hamsters' memories`,
    `Robot dogs`,
    `Computers that record our dreams`,
    `World governments`,
    `Chrome eggs with screens`,
    `Contact lenses`,
    `Chemicals in our meat`,
    `The ultra wealthy`,
    `Our social media popularity levels`,
    `LinkedIn connections`,
    `Drones`,
    `Memory capture devices`,
    `Surveillance cameras`,
    `Internet browsers`,
    `The ultra poor`,
    `Racist robots`,
    `Cyber bullies`,
    `Credit-based value systems`,
    `1980’s lesbians`,
    `Our own memories`,
    `Video games`,
    `The rules of a video game`,
    `Data visualizations on cool see-through screens`,
    `Lifelike clone robots`,
    `John Hamm and a roomba`,
    `Cryptocurrencies`,
    `Collective hiveminds`,
    `Simulations`,
    `A.I.s`,
    `Mysterious figures`,
    `Celebrities`,
    `Lasers`,
    `Smart refrigerators`,
    `Sexy Scandinavian apartments`,
    `Talent competitions`,
    `Online avatars`,
    `Mysterious algorithms`,
    `Internet service providers`,
    `Autonomous vehicles`,
    `Instant delivery services`,
    `Nanobots`,
    `Brain implants`,
    `Exercise bikes`,
    `Webcams`,
    `Cyber terrorists`,
    `Guns with feelings`,
    `Our genomes`,
    `A.I. assistants`
];

const actions = [
    `hunt and kill ugly people`,
    `judge your self-worth`,
    `brainwash children through hypnosis`,
    `decide who gets laid`,
    `decide what we eat`,
    `blackmail anyone in love`,
    `race against the clock`,
    `produce a juice that’s actually mind control`,
    `determine the quality of our orgasms`,
    `run for president`,
    `are the only thing worth any money`,
    `decides how long people live`,
    `livestream your private videos`,
    `turn the elderly into robots`,
    `require everyone to be online at all times`,
    `turn emotions into crimes`,
    `trick soldiers through mind control`,
    `determine your worth in society`,
    `make all your decisions for you`,
    `know everything you’ve done online`,
    `gain the trust of everyone`,
    `determine how much you are paid`,
    `turn evil`,
    `ration out knowledge`,
    `organize mandatory orgies`,
    `police our thoughts`,
    `make all our medical decisions`,
    `determine what job you have`,
    `tell us what everyone really thinks of us`,
    `tell us what our pets our thinking`,
    `determine who can have children`,
    `decide who lives and dies`,
    `decide when we die`,
    `require all our natural resources`,
    `destroy the environment`,
    `cause the end of religion`,
    `play the marry f*ck kill game for real`,
    `literally extract people’s souls`,
    `create an egalitarian society`,
    `require microtransactions to use them`,
    `replace every teacher`,
    `compete for our amusement`,
    `let us replay all our memories`,
    `push a middle aged woman to murder`,
    `deliver anything you could ever want`,
    `tear a family apart`,
    `lead to a deadly love triangle`,
    `trick soldiers into killing`,
    `put ad blockers on our vision`,
    `censor what we can and can't smell`,
    `allow us to communicate telepathically`
];

const twists = [
    `but actually it’s 500 years ago`,
    `but really it’s a simulation`,
    `but only in virtual reality`,
    `on the moon`,
    `but then everyone’s memory is wiped`,
    `but at the cost of our freedom`,
    `but really it’s our own fault`,
    `but some of them are evil`,
    `but believe they are doing the right thing`,
    `but really it’s a simulation inside a simulation`,
    `but everyone is in VR so it doesn’t matter`,
    `but if you die in the simulation you die in real life`,
    `except it never actually happened`,
    `inside a video game`,
    `but love wins... maybe`,
    `and no one cares because that’s just, like, a normal thing in this world`,
    `but only minorities are the victim`,
    `but the real villain is society`,
    `but in the end you're not sure if it really happened or not`,
    `but only if you give up 10 years of your life`,
    `but only the wealthy benefit`,
    `unless you wear a little computer on your temple`,
    `but only on the internet`,
    `but really the robots are more human than we are`,
    `but we forget how to feel love`,
    `but we forget what real meat tastes like`,
    `but it destroys the environment`,
    `but almost everyone dies`,
    `but it’s all one child’s nightmare`,
    `unless you kill three people`,
    `but really the opposite happens`,
    `until you wake up`,
    `unless you pay microtransactions`,
    `but really it’s a metaphor for social media today`,
    `but really it’s a metaphor for cyberbullying`,
    `but really it’s a metaphor for racism`,
    `and it’s terrifying (but there are funny parts)`,
    `but you can enter a simulation where the opposite is true`,
    `but it resets every night at midnight`,
    `but only on Christmas Eve`,
    `but you'll be blind if you don't comply`,
    `but you'll be banished from society if you don't play along`,
];

export default { subjects, actions, twists };